var newsfeed = [
  {
    exercise_name: "Sentadilla Bulgara con Salto - Pierna Drch",
    videosrc: "src/sent-bulg-salt.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Bulgara con Salto - Pierna Izq",
    videosrc: "src/sent-bulg-salt.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Isometrica en Pared",
    videosrc: "src/squat-iso-5s.mp4",
    limitrep: 12,
    tiempopreparacion: 20,
  },
  {
    exercise_name: "Ys",
    videosrc: "src/Ys.mp4",
    limitrep: 15,
    tiempopreparacion: 20,
  },
  {
    exercise_name: "Flexiones",
    videosrc: "src/flexion.mp4",
    limitrep: 15,
    tiempopreparacion: 20,
  }, 
  {
    exercise_name: "Puente de Isquios en silla - Pierna Drch",
    videosrc: "src/puente-gluteo-uni.mp4",
    limitrep: 8,
    tiempopreparacion: 30,
  },
  {
    exercise_name: "Puente de Isquios en silla - Pierna Izq",
    videosrc: "src/puente-gluteo-uni.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Bulgara con Salto - Pierna Drch",
    videosrc: "src/sent-bulg-salt.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Bulgara con Salto - Pierna Izq",
    videosrc: "src/sent-bulg-salt.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Isometrica en Pared",
    videosrc: "src/squat-iso-5s.mp4",
    limitrep: 12,
    tiempopreparacion: 20,
  },
  {
    exercise_name: "Ys",
    videosrc: "src/Ys.mp4",
    limitrep: 15,
    tiempopreparacion: 20,
  },
  {
    exercise_name: "Flexiones",
    videosrc: "src/flexion.mp4",
    limitrep: 15,
    tiempopreparacion: 20,
  }, 
  {
    exercise_name: "Puente de Isquios en silla - Pierna Drch",
    videosrc: "src/puente-gluteo-uni.mp4",
    limitrep: 8,
    tiempopreparacion: 30,
  },
  {
    exercise_name: "Puente de Isquios en silla - Pierna Izq",
    videosrc: "src/puente-gluteo-uni.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Bulgara con Salto - Pierna Drch",
    videosrc: "src/sent-bulg-salt.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Bulgara con Salto - Pierna Izq",
    videosrc: "src/sent-bulg-salt.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
  {
    exercise_name: "Sentadilla Isometrica en Pared",
    videosrc: "src/squat-iso-5s.mp4",
    limitrep: 12,
    tiempopreparacion: 20,
  },
  {
    exercise_name: "Ys",
    videosrc: "src/Ys.mp4",
    limitrep: 15,
    tiempopreparacion: 20,
  },
  {
    exercise_name: "Flexiones",
    videosrc: "src/flexion.mp4",
    limitrep: 15,
    tiempopreparacion: 20,
  }, 
  {
    exercise_name: "Puente de Isquios en silla - Pierna Drch",
    videosrc: "src/puente-gluteo-uni.mp4",
    limitrep: 8,
    tiempopreparacion: 30,
  },
  {
    exercise_name: "Puente de Isquios en silla - Pierna Izq",
    videosrc: "src/puente-gluteo-uni.mp4",
    limitrep: 8,
    tiempopreparacion: 10,
  },
];		

var frases = ["Monto, eres un máquina, sigue así!"]
